[General Settings]

# Prefix for chat messages
CHAT_PREFIX = [MIX]

# How much rounds will be played in overtime. x for each side.
OVERTIME_ROUNDS = 3

# Score needed to be equal in order overtime can be available.
OVERTIME_SCORE = 15

# End score (First to 16 rounds)
MIX_END_ROUND = 16

# Flags that an admin needs to have in order to can chat
ADMIN_CHAT_FLAGS = c

# Flags that an admin needs in order to access commands
ADMIN_LEVEL_ACCESS = c

# Freezetime when teams are changing sides.
FREEZE_TIME_SWAP = 10

# Turn on automatic overtime? 	0 - No | 1 - Yes
AUTOMATIC_OVERTIME = 1

# Start Mix Config
START_CONFIG = start.cfg

# Stop / Warm / Knife Config
STOP_CONFIG = stop.cfg

# Standard round freezetime
FREEZETIME = 15

# Tactical Pause Duration in seconds
PAUSE_DURATION = 60

# Knife round side selection vote delay (seconds)
KNIFE_ROUND_START_DELAY = 10

# Force warmup if the map changes or not in a match
# 0 - No | 1 - Yes
FORCE_WARMUP = 1

[Commands Section]

# Note: All commands separated by ','
SHOW_COMMANDS = say /comenzi, say_team /comenzi

# Start Mix Commands
START_MIX_COMMANDS = say /mix, say_team /mix, say /start, say_team /start

# Stop Mix Commands
STOP_MIX_COMMANDS = say /stop, say_team /stop

# WarmUp / Deathmatch Practice Commands
WARM_COMMANDS = say /dm1, say_team /dm1, say /warm, say_team /warm

# Knife Round Commands
KNIFE_COMMANDS = say /knife, say_team /knife

# Chat Mix Commands (Turn Chat ON)
CHAT_ON_COMMANDS = say /on, say_team /on

# Chat Mix Commands (Turn Chat OFF)
CHAT_OFF_COMMANDS = say /off, say_team /off

# Overtime Commands
OVERTIME_COMMANDS = say /overtime, say_team /overtime, say /prelungiri, say_team /prelungiri

# Password On Commands
PASSWORD_ON_COMMANDS = say /passon, amx_passon

# Password OFF Commands
PASSWORD_OFF_COMMANDS = say /passoff, amx_passoff

# Spectate All Players Commands
SPECALL_COMMANDS = say /specall, say_team /specall, amx_specall

# Restart Commands
RESTART_COMMANDS = say /rr, say /restart

# Score Commands 
SCORE_COMMANDS = say /score, say_team /score

# Move Commands
MOVE_CT_COMMANDS = amx_ct
MOVE_TERO_COMMANDS = amx_t
MOVE_SPEC_COMMANDS = amx_spec

# Pause / Tactical Timeout Commands
PAUSE_COMMANDS = say /pause, say_team /pause, say /pauza, say_team /pauza

[Warm Settings]

# WarmUp Player's Spawn Money ($16,000 full buy practice)
WARMUP_SPAWN_MONEY = 16000

# WarmUp round gameplay: normal competitive round elimination reset
WARMUP_TYPE = 0

[Hud Settings]

# Teammate's Money HUD Color | R G B
HUD_COLOR = 100 200 0

# Teammate's Money HUD Position | x0y Axis
HUD_POSITION = 0.05 0.35
