; Weapons and Equipment Restriction File
; Managed by AMX Mod X

; Equipment
nvgs             ; NightVision Goggles
shield           ; Tactical Shield

; Snipers
sg550            ; Sig SG-550 Sniper
g3sg1            ; H&K G3/SG-1 Sniper Rifle
m249             ; FN M249 Para
